name: CI

on:
  - pull_request
  - push
jobs:
  test:
    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3', '8.4']
        dependencies: ['']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: simplexml, geospatial, pcov
          coverage: pcov
          tools: composer:v2
      - name: Install dependencies
        run: composer update --no-progress --prefer-dist --optimize-autoloader ${{matrix.dependencies}}
      - name: Psalm
        run: php vendor/bin/psalm --output-format=github --php-version=${{ matrix.php-versions }}
      - name: PHPUnit
        run: php vendor/bin/phpunit
